version: '3.4'

networks:
  howtocodewell:

volumes:
  webserver_cache:
  webserver_logs:

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - howtocodewell_fm
    restart: always
    volumes:
      - /data/ssl_certs:/var/lib/https-portal
    networks:
      - howtocodewell
    environment:
      DOMAINS: "howtocodewell.fm -> http://howtocodewell_fm"
      STAGE: production
      FORCE_RENEW: 'false'

  howtocodewell_fm:
    image: howtocodewell/howtocodewell-fm:latest
    restart: always
    container_name: howtocodewell_fm
    volumes:
      - ./temp:/var/www/html/public/.well-known/acme-challenge
      - .:/var/www/html
      - webserver_cache:/var/www/html/var/cache:Z
      - webserver_logs:/var/www/html/var/log:Z
      - ./infra/docker/prod/apache/config/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./infra/docker/prod/php/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - howtocodewell
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - APP_ENV=prod

  node:
    image: node:16
    volumes:
      - .:/app
    networks:
      - howtocodewell

  composer:
    image: howtocodewell/composer:php-8
    working_dir: /var/www/html
    networks:
      - howtocodewell
    volumes:
      - .:/app