name: Staging CI

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

  workflow_dispatch:

jobs:
  checks:
    name: Pre Build Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: http, redis, zip
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}
      - run: composer install --prefer-dist --no-interaction
      - run: ./vendor/bin/phpstan analyse

  unit_tests:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - uses: actions/checkout@v2
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "/home/runner/work/website/website/.env.local"
          FILE_DATA: ""
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: http, redis, zip
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}
      - run: composer install --prefer-dist --no-interaction
      - run: ./vendor/bin/phpunit analyse

  build:
    name: Build and push
    runs-on: ubuntu-latest
    needs: [checks, unit_tests]
    steps:
      - uses: actions/checkout@v2
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6
      - run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn run build
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      -
        name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: howtocodewell/howtocodewell-fm:staging,howtocodewell/howtocodewell-fm:staging-${{ env.SHA }}
